using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Model.Definition
{
    /// <summary>
    /// Enum of different discipline name matching their JobMine discipline number
    /// </summary>
    public enum DisciplineEnum : byte
    {
        UnAssigned = 0,
        AHSUnspecified = 4,
        AHSHealthPromotion = 110,
        AHSHealthStudiesAndGerontology = 5,
        AHSKinesiology = 6,
        AHSRecLeisureStudies = 7,
        AHSRecBusinessManagement = 8,
        ARCHArchitecture = 31,
        ARTSMASTERSEconomics = 92,
        ARTSMASTERSExpDigitalMedia = 90,
        ARTSMASTERSLiteraryStudies = 88,
        ARTSMASTERSPoliticalScience = 102,
        ARTSMASTERSPublicService = 91,
        ARTSMASTERSRhetCommDesign = 89,
        ARTSUnspecified = 9,
        ARTSAnthropology = 10,
        ARTSArtsAndBusiness = 68,
        ARTSDigitalArtsComm = 77,
        ARTSEconomics = 11,
        ARTSEnglish = 13,
        ARTSEnglishLitAndRhetoric = 107,
        ARTSFinancialManagement = 76,
        ARTSGlobalEngagement = 108,
        ARTSHRManagement = 15,
        ARTSHistory = 14,
        ARTSInternationalTrade = 106,
        ARTSLegalStudies = 112,
        ARTSManagementAccounting = 80,
        ARTSMathematicalEconomics = 111,
        ARTSPhilosophy = 78,
        ARTSPoliticalScience = 16,
        ARTSPsychology = 17,
        ARTSRhetoricAndProfWriting = 69,
        ARTSSociology = 18,
        ARTSSpeechCommunication = 113,
        AllBusinessUnSpecified = 65,
        AllFinanceUnSpecified = 109,
        AllHealthInformatics = 81,
        AllInfoTechUnSpecified = 66,
        CAChartProfAcctCPA = 2,
        ENGMASTERSCivil = 94,
        ENGMASTERSManagementScience = 93,
        ENGUnSpecified = 19,
        ENGChemical = 20,
        ENGCivil = 21,
        ENGComputer = 22,
        ENGElectrical = 23,
        ENGEnvironmental = 82,
        ENGGeological = 26,
        ENGManagement = 83,
        ENGMechanical = 28,
        ENGMechatronics = 70,
        ENGNanotechnology = 79,
        ENGSoftware = 45,
        ENGSystemsDesign = 29,
        ENVUnSpecified = 30,
        ENVEnvAndResourceStudies = 32,
        ENVEnvironmentAndBusiness = 71,
        ENVGeogAndEnvManagement = 33,
        ENVGeomatics = 84,
        ENVInternationalDevelopment = 97,
        ENVKnowledgeIntegration = 96,
        ENVPlanning = 34,
        MATHMASTERSHealthInfo = 95,
        MATHUnspecified = 36,
        MATHActuarialScience = 35,
        MATHAppliedMathematics = 37,
        MATHBioinformatics = 38,
        MATHBusinessAdministration = 39,
        MATHCombinatoricsAndOptimizat = 40,
        MATHComputationalMath = 72,
        MATHComputerScience = 41,
        MATHComputingAndFinancialMgm = 104,
        MATHFinAnalysisAndRiskMgmt = 101,
        MATHITManagement = 98,
        MATHMathematicalEconomics = 99,
        MATHMathematicalFinance = 100,
        MATHMathematicalOptimization = 42,
        MATHMathematicalPhysics = 73,
        MATHMathematicalStudies = 74,
        MATHPureMathematics = 43,
        MATHScientificComputation = 44,
        MATHStatistics = 46,
        MATHStatisticsforHealth = 105,
        MATHTeaching = 63,
        SCIUnspecified = 47,
        SCIBiochemistry = 48,
        SCIBioinformatics = 49,
        SCIBiology = 50,
        SCIBiotechnologyEconomics = 51,
        SCIChemistry = 52,
        SCIEarthSciences = 53,
        SCIEnvironmentalScience = 54,
        SCIGeologyandHydrogeology = 56,
        SCIOptometry = 87,
        SCIPharmacy = 86,
        SCIPhysics = 58,
        SCIPsychology = 103,
        SCIScienceBusiness = 60
    }
    public partial class GlobalDef
    {
        /// <summary>
        /// Maximum number of discipline a single job can have (may change according to JobMine or expansion)
        /// </summary>
        public const int MaxNumberOfDisciplinesPerJob = 5;

        /// <summary>
        /// Total Number of Disciplines (may change according to JobMine)
        /// </summary>
        public int NumberOfDisciplines
        {
            get { return DisciplinesNames.Count; }    
        }

        /// <summary>
        /// Highest JobMine discipline number represented in the DisciplineEnum
        /// </summary>
        public const int HighestDisciplineEnumNumber = 113;

        /// <summary>
        /// List of discipline names using their JobMine discipline number as key. Value is the name show on JobMine Job Inquiry
        /// </summary>
        public static Dictionary<byte, string> DisciplinesNames = new Dictionary<byte, string>
        {
            {4,"AHS-(unspecified)"},
            {110,"AHS-Health Promotion"},
            {5,"AHS-Hlth Studies & Gerontology"},
            {6,"AHS-Kinesiology"},
            {7,"AHS-Rec. & Leisure Studies"},
            {8,"AHS-Rec./Business Management"},
            {31,"ARCH-Architecture"},
            {92,"ARTS MASTERS-Economics"},
            {90,"ARTS MASTERS-Exp Digital Media"},
            {88,"ARTS MASTERS-Literary Studies"},
            {102,"ARTS MASTERS-Political Science"},
            {91,"ARTS MASTERS-Public Service"},
            {89,"ARTS MASTERS-Rhet/Comm Design"},
            {9,"ARTS-(unspecified)"},
            {10,"ARTS-Anthropology"},
            {68,"ARTS-Arts & Business"},
            {77,"ARTS-Digital Arts Comm"},
            {11,"ARTS-Economics"},
            {13,"ARTS-English"},
            {107,"ARTS-English Lit & Rhetoric"},
            {76,"ARTS-Financial Management"},
            {108,"ARTS-GlobalDef Engagement"},
            {15,"ARTS-HR Management"},
            {14,"ARTS-History"},
            {106,"ARTS-International Trade"},
            {112,"ARTS-Legal Studies"},
            {80,"ARTS-Management Accounting"},
            {111,"ARTS-Mathematical Economics"},
            {78,"ARTS-Philosophy"},
            {16,"ARTS-Political Science"},
            {17,"ARTS-Psychology"},
            {69,"ARTS-Rhetoric & Prof Writing"},
            {18,"ARTS-Sociology"},
            {113,"ARTS-Speech Communication"},
            {65,"All Business (unspecified)"},
            {109,"All Finance (unspecified)"},
            {81,"All Health Informatics"},
            {66,"All Info Tech (unspecified)"},
            {2,"CA-Chart Prof Acct (CPA)"},
            {94,"ENG MASTERS-Civil"},
            {93,"ENG MASTERS-Management Science"},
            {19,"ENG-(unspecified)"},
            {20,"ENG-Chemical"},
            {21,"ENG-Civil"},
            {22,"ENG-Computer"},
            {23,"ENG-Electrical"},
            {82,"ENG-Environmental"},
            {26,"ENG-Geological"},
            {83,"ENG-Management"},
            {28,"ENG-Mechanical"},
            {70,"ENG-Mechatronics"},
            {79,"ENG-Nanotechnology"},
            {45,"ENG-Software"},
            {29,"ENG-Systems Design"},
            {30,"ENV- (unspecified)"},
            {32,"ENV-Env & Resource Studies"},
            {71,"ENV-Environment & Business"},
            {33,"ENV-Geog & Env Management"},
            {84,"ENV-Geomatics"},
            {97,"ENV-International Development"},
            {96,"ENV-Knowledge Integration"},
            {34,"ENV-Planning"},
            {95,"MATH MASTERS-Health Info"},
            {36,"MATH- (unspecified)"},
            {35,"MATH-Actuarial Science"},
            {37,"MATH-Applied Mathematics"},
            {38,"MATH-Bioinformatics"},
            {39,"MATH-Business Administration"},
            {40,"MATH-Combinatorics & Optimizat"},
            {72,"MATH-Computational Math"},
            {41,"MATH-Computer Science"},
            {104,"MATH-Computing & Financial Mgm"},
            {101,"MATH-Fin Analysis & Risk Mgmt"},
            {98,"MATH-IT Management"},
            {99,"MATH-Mathematical Economics"},
            {100,"MATH-Mathematical Finance"},
            {42,"MATH-Mathematical Optimization"},
            {73,"MATH-Mathematical Physics"},
            {74,"MATH-Mathematical Studies"},
            {43,"MATH-Pure Mathematics"},
            {44,"MATH-Scientific Computation"},
            {46,"MATH-Statistics"},
            {105,"MATH-Statistics for Health"},
            {63,"MATH-Teaching"},
            {47,"SCI- (unspecified)"},
            {48,"SCI-Biochemistry"},
            {49,"SCI-Bioinformatics"},
            {50,"SCI-Biology"},
            {51,"SCI-Biotechnology/Economics"},
            {52,"SCI-Chemistry"},
            {53,"SCI-Earth Sciences"},
            {54,"SCI-Environmental Science"},
            {56,"SCI-Geology and Hydrogeology"},
            {87,"SCI-Optometry"},
            {86,"SCI-Pharmacy"},
            {58,"SCI-Physics"},
            {103,"SCI-Psychology"},
            {60,"SCI-Science/Business"}
        };
    }
}
