//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF.ClusterDB.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public int JobId { get; set; }
        public byte Discipline1 { get; set; }
        public byte Discipline2 { get; set; }
        public byte Discipline3 { get; set; }
        public byte Discipline4 { get; set; }
        public byte Discipline5 { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
