//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF.ClusterDB.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerReview
    {
        public EmployerReview()
        {
            this.JobReviews = new HashSet<JobReview>();
        }
    
        public int EmployerId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<JobReview> JobReviews { get; set; }
    }
}
