//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF.ClusterDB.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public string Comment { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> Employer_Id { get; set; }
        public Nullable<int> Location_Id { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual Location Location { get; set; }
        public virtual Level Level { get; set; }
    }
}
