//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF.ClusterDB.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRating
    {
        public int JobRatingId { get; set; }
        public string Comment { get; set; }
        public double Rating { get; set; }
        public string Date { get; set; }
        public string Salary { get; set; }
        public Nullable<int> JobReview_JobReviewId { get; set; }
    
        public virtual JobReview JobReview { get; set; }
    }
}
