//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF.ClusterDB.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobReview
    {
        public JobReview()
        {
            this.JobRatings = new HashSet<JobRating>();
        }
    
        public int JobReviewId { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public string AverageSalary { get; set; }
        public string SalaryRange { get; set; }
        public int NumberOfReviews { get; set; }
        public int Popularity { get; set; }
        public string JobDescription { get; set; }
        public int AverageRating { get; set; }
        public Nullable<int> Employer_EmployerId { get; set; }
    
        public virtual EmployerReview EmployerReview { get; set; }
        public virtual ICollection<JobRating> JobRatings { get; set; }
    }
}
